### ISSUE TITLE
New version bugs

### ISSUE THREAD

**Issue by Kebechet** [horsicq/Detect-It-Easy#63]
Firstly thank you for this great update.

**My DIE version:** die_win32_portable_3.00.zip
**My OS:** Windows 10 Build 18362

**Question** 
Is Yara scanning still available in this release ? (I don't see it)

**Improvement 1** 
Please can you specify in README what is the difference between release with and without loader(what is loader good for) ? Especially when many AV engines detect build with loader as malware. 

**Improvement 2** 
The new(white) default theme doesn't look as good as the Orange one. Wouldn't be better to set that one as a default ?

**BUG 1**
DIE doesn't detect .NET GUIDs properly. 
.NET GUID is project identifier which has format \w{8}-\w{4}-\w{4}-\w{4}-\w{12}

- in VisualStudio you can find it in Project->Project Properties->Application->Assembly information http://prntscr.com/tz4xkp
- in DIE HEX: http://prntscr.com/tz50qu
- what DIE thinks is a GUID http://prntscr.com/tz529s

**BUG 2**
in DIE->HEX shortcut CTRL+F doesn't work for me(only rightClick->find).
but in DIE->PE->HEX it works without any problem

**Comment by horsicq** [comment]
Thanks a lot for the bugreport! The version 3.00 is a little buggy. I rewrote 95% code of version 2.06.

> Is Yara scanning still available in this release ? (I don't see it)

I removed it because some people claimed false detects. May be I will add it to one of the next versions of DiE again but I have to check and edit some YARA rules.

> Please can you specify in README what is the difference between release with and without loader(what is loader good for) ? Especially when many AV engines detect build with loader as malware.

The only difference the version with loader has die.exe in the root that runs "base/die.exe"
I added this information to README.MD The next version of DiE will be without loader.

> The new(white) default theme doesn't look as good as the Orange one. Wouldn't be better to set that one as a default ?

The Orange theme will be default in the next version.

> DIE doesn't detect .NET GUIDs properly.
> .NET GUID is project identifier which has format \w{8}-\w{4}-\w{4}-\w{4}-\w{12}
> 
> * in VisualStudio you can find it in Project->Project Properties->Application->Assembly information http://prntscr.com/tz4xkp
> * in DIE HEX: http://prntscr.com/tz50qu
> * what DIE thinks is a GUID http://prntscr.com/tz529s

I will take a look.

> in DIE->HEX shortcut CTRL+F doesn't work for me(only rightClick->find).
> but in DIE->PE->HEX it works without any problem

I will fix it.
